const gallery_array = [
  {
    label: "City Park",
    code: "city_park",
    img: "1.jpg",
  },
  {
    label: "KDMC School",
    code: "kdmc_school_work",
    img: "1.jpg",
  },
  {
    label: "La Pinos Pizza",
    code: "la_pinoz_pizza_ulhasnagar",
    img: "1.JPG",
  },
  {
    label: "Wall Painting (Thakur village, Kandivali)",
    code: "thakur_village_kandivali",
    img: "1.jpeg",
  },
  {
    label: "Altizza (Kalyan)",
    code: "altizza_kalyan",
    img: "1.JPG",
  },
  {
    label: "Baby Room Kalyan",
    code: "baby_room_kalyan",
    img: "1.jpg",
  },
  {
    label: "Balbharti School (Kandivali)",
    code: "balbharti_school_kandivali",
    img: "1.JPG",
  },
  {
    label: "Barave Village KDMC (Kalyan)",
    code: "barave_village_kdmc_kalyan",
    img: "1.jpg",
  },
  {
    label: "Barave Village Raunak City",
    code: "barave_village_raunak_city",
    img: "1.jpg",
  },
  {
    label: "Borivali East",
    code: "borivali_east",
    img: "1.jpeg",
  },
  {
    label: "Goregaon Furniture Showroom",
    img: "1.jpg",
    code: "goregaon_showroom",
  },
  {
    label: "Hospital Shashtri Nagar Dombivali",
    img: "1.jpg",
    code: "hospital_shashtri_nagar_dombivali",
  },
  {
    label: "KDMC Building Kalyan",
    img: "1.jpg",
    code: "kdmc_building_kalyan",
  },
  {
    label: "KDMC Elect Department",
    img: "1.jpg",
    code: "kdmc_elect_dept",
  },
  {
    label: "KDMC Sabhagruh FAB",
    img: "1.jpg",
    code: "kdmc_sabhagruh_fab",
  },
  {
    label: "KDMC Sir Off",
    img: "1.jpg",
    code: "kdmc_sir_off",
  },
  {
    label: "KDMC Waste Management Dept",
    img: "1.jpg",
    code: "kdmc_wast_mang_dept",
  },
  {
    label: "KDMC Water Dept",
    img: "1.jpg",
    code: "kdmc_water_dept",
  },
  {
    label: "Omkar Altamonte Malad",
    img: "1.JPG",
    code: "omkar_altamonte_malad",
  },
  {
    label: "Physiotherapy Clinic",
    img: "1.jpg",
    code: "physiotherapy_clinic",
  },
  {
    label: "Priyasi Ulhasnagar",
    img: "1.JPG",
    code: "priyasi_ulhasnagar",
  },
  {
    label: "Rukmini Bai Hospital Kalyan",
    img: "1.jpg",
    code: "rukmini_baI_hospital_kalyan",
  },
  {
    label: "Simpoli Borivali",
    img: "1.JPG",
    code: "simpoli_borivali",
  },
];

const image_tags = {
  city_park: [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
    "12.jpg",
  ],
  kdmc_school_work: [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
    "11.jpg",
  ],
  altizza_kalyan: ["1.JPG", "2.JPG", "3.JPG", "4.JPG"],
  baby_room_kalyan: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"],
  balbharti_school_kandivali: [
    "1.JPG",
    "2.JPG",
    "3.JPG",
    "4.JPG",
    "5.jpeg",
    "6.jpeg",
  ],
  barave_village_kdmc_kalyan: [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
  ],
  barave_village_raunak_city: [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
    "9.jpg",
    "10.jpg",
  ],
  borivali_east: ["1.jpeg", "2.jpeg", "3.jpeg"],
  goregaon_showroom: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
  hospital_shashtri_nagar_dombivali: ["1.jpg", "2.jpg", "3.jpg"],
  kdmc_building_kalyan: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
  kdmc_elect_dept: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
  kdmc_sabhagruh_fab: [
    "1.jpg",
    "2.jpg",
    "3.jpg",
    "4.jpg",
    "5.jpg",
    "6.jpg",
    "7.jpg",
    "8.jpg",
  ],
  kdmc_sir_off: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg", "6.jpg"],
  kdmc_wast_mang_dept: ["1.jpg", "2.jpg", "3.jpg", "4.jpg", "5.jpg"],
  kdmc_water_dept: ["1.jpg", "2.jpg"],
  la_pinoz_pizza_ulhasnagar: ["1.JPG", "2.JPG", "3.JPG", "4.JPG"],
  omkar_altamonte_malad: ["1.JPG", "2.JPG"],
  physiotherapy_clinic: ["1.jpg", "2.jpg", "3.jpg", "4.jpeg"],
  priyasi_ulhasnagar: ["1.JPG", "2.JPG", "3.JPG", "4.JPG"],
  rukmini_baI_hospital_kalyan: ["1.jpg", "2.jpg"],
  simpoli_borivali: ["1.JPG"],
  thakur_village_kandivali: ["1.jpeg", "2.jpeg"],
};
